/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NaiveProvider: typeof import('./../src/components/Common/NaiveProvider.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NCheckbox: typeof import('naive-ui')['NCheckbox'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NInput: typeof import('naive-ui')['NInput'];
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
