/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NaiveProvider: typeof import('./../src/components/Common/NaiveProvider.vue')['default'];
    NAvatar: typeof import('naive-ui')['NAvatar'];
    NBadge: typeof import('naive-ui')['NBadge'];
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb'];
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem'];
    NButton: typeof import('naive-ui')['NButton'];
    NCard: typeof import('naive-ui')['NCard'];
    NCheckbox: typeof import('naive-ui')['NCheckbox'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDataTable: typeof import('naive-ui')['NDataTable'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NDropdown: typeof import('naive-ui')['NDropdown'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NGrid: typeof import('naive-ui')['NGrid'];
    NGridItem: typeof import('naive-ui')['NGridItem'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NInput: typeof import('naive-ui')['NInput'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider'];
    NMenu: typeof import('naive-ui')['NMenu'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
    NScrollbar: typeof import('naive-ui')['NScrollbar'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NTabPane: typeof import('naive-ui')['NTabPane'];
    NTabs: typeof import('naive-ui')['NTabs'];
    NTimeline: typeof import('naive-ui')['NTimeline'];
    NTimelineItem: typeof import('naive-ui')['NTimelineItem'];
    NTooltip: typeof import('naive-ui')['NTooltip'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
